### ISSUE TITLE
Support for refile

### ISSUE THREAD

**Issue by Atreus-Tantalus** [alphapapa/helm-org-rifle#26]
This is by far the best search interface for org files, thank you very much for developing it! Only thing that is missing, is refiling function, could you implement it?

**Comment by alphapapa** [comment]
That's a good idea, thanks.  I tested it briefly and it seems to work for me.  Please let me know how it works for you.

**Comment by Atreus-Tantalus** [comment]
That's not what i meant. Sorry for not being clear enough.  :D

I meant using org-rifle as a replacement for helm-org-refile interface. It would be great if you could make function, say org-rifle-refile, that would function just like regular helm-org-refile: invoke command - find headline - press return, and headline caret was on gets refiled!

Org-rifle fontification makes finding headline i want to refile way quicker. :)

Thanks again for creating and maintaining this package. Its really useful!

**Comment by alphapapa** [comment]
Ok, we seem to be misunderstanding each other.

IIUC, what you want is to use `helm-org-rifle` to choose a refile **target**.  That would be possible, however...

You seem to want this because:

> Org-rifle fontification makes finding headline i want to refile way quicker.

But `helm-org` itself can fontify headings; `helm-org-rifle` is not unique in doing so.  So you could use `helm-org-in-buffer-headings` or `helm-org-agenda-files-headings` to choose a refile target.

Do you see what I mean?
