### ISSUE TITLE
Running helm-org-rifle at point?

### ISSUE THREAD

**Issue by georgewsinger** [alphapapa/helm-org-rifle#27]
Is there a way to run helm-org-rifle at point, so that if, i.e., the cursor is on the word "word" we will search for all org occurences of "word"?

**Comment by alphapapa** [comment]
Hi,

The default keymap for `helm-org-rifle` is a copy of `helm-map`, so you can press `C-w` to use `helm-yank-text-at-point` to yank the word after point into the minibuffer.  

I think that's probably better than having it automatically use the word at point, because if that's not what the user wants, it would cause a delay while searching for that word, and then the user would have to clear the word before typing.

However, if you would prefer to do it automatically, you can add `:input (thing-at-point 'word)` to the call to `helm` in the `helm-org-rifle-define-command` macro, then re-eval the buffer, and all of the commands will do so automatically.

```el
(cl-defmacro helm-org-rifle-define-command (name args docstring &key sources (let nil) (transformer nil))
  "Define interactive helm-org-rifle command, which will run the appropriate hooks.
Helm will be called with vars in LET bound."
  `(cl-defun ,(intern (concat "helm-org-rifle" (when (s-present? name) (concat "-" name)))) ,args
     ,docstring
     (interactive)
     (unwind-protect
         (progn
           (run-hooks 'helm-org-rifle-before-command-hook)
           (let* ((helm-candidate-separator " ")
                  ,(if transformer
                       ;; I wish there were a cleaner way to do this,
                       ;; because if this `if' evaluates to nil, `let' will
                       ;; try to set `nil', which causes an error.  The
                       ;; choices seem to be to a) evaluate to a list and
                       ;; unsplice it (since unsplicing `nil' evaluates to
                       ;; nothing), or b) return an ignored symbol when not
                       ;; true.  Option B is less ugly.
                       `(helm-org-rifle-transformer ,transformer)
                     'ignore)
                  ,@let)
             (helm :sources ,sources
                   :input (thing-at-point 'word))))  ; <--
       (run-hooks 'helm-org-rifle-after-command-hook))))
```

**Comment by alphapapa** [comment]
Closing now, but feel free to continue discussion.  Thanks.

**Comment by georgewsinger** [comment]
Similar to above, is there a way to make a command to just jump to the first match that `helm-org-rifle` finds for the word at point?

**Comment by alphapapa** [comment]
You could make such a command, but the matches are not sorted by relevance, so it might not be very useful.
